### PR TITLE
View all drives and login/singup

### PR DESCRIPTION
**Pull request by SandeepVasireddy**
Created the functionality for login/signup and the db.py. Also created the view all drives within the userprofile

### CODE REVIEW

**Comment by sophtank** [comment]
Currently experiencing a psycopg_pool.PoolTimeout error. Perhaps you have the same issue in your code that Krevat had in his demo?
image
image

**Comment by Ashleigh0204** [comment]
It works on my end.  I would recommend adding the user's name to the profile and making it drive # instead of vehicle #.

**Comment by SandeepVasireddy** [comment]
Just fixed those

**Comment by Matt5008906** [comment]
This looks good to me to merge, only minor suggestion I would give is just adding some validation logic with 404s etc. in app.py.

**Pull request merged**
