### PR TITLE
Edit drive

### PR DESCRIPTION
**Pull request by Zzz4nder**
added Edit Drive Functionality.

Looks like I wrote more code than I did because I tired to manually update the branch with all the new commits, and its showing everyone's work as my own. Shouldn't be an issue since I'll have to manually merge the branches so ill only merge my edits.

### CODE REVIEW

**Comment by Ashleigh0204** [comment]
A few comments:
1. I think you are using an outdated version of the project.  The functionalities added in Sprint 2 are not there.  If that's just bc your code merged weirdly, then no big deal until you can make a pull from main.  But do not merge directly or it will not preserve all sprint 2 work.
2.  I think it would be nicer to include the previous data as actual field in the text boxes instead of placeholders.  That way if I just want to correct a spelling error I don't have to retype the entire field.
3. Are the dates remaining the same?  When I edit drive 1, it switches to location drive 2 almost as if the time is being updated to the current time.  Not sure if that is your issue or not, but the drives are still switching places.
4. The tags are not automatically checked inside of the form.

**Comment by Zzz4nder** [comment]
> A few comments:
> 
>     1. I think you are using an outdated version of the project.  The functionalities added in Sprint 2 are not there.  If that's just bc your code merged weirdly, then no big deal until you can make a pull from main.  But do not merge directly or it will not preserve all sprint 2 work.
> 
>     2. I think it would be nicer to include the previous data as actual field in the text boxes instead of placeholders.  That way if I just want to correct a spelling error I don't have to retype the entire field.
> 
>     3. Are the dates remaining the same?  When I edit drive 1, it switches to location drive 2 almost as if the time is being updated to the current time.  Not sure if that is your issue or not, but the drives are still switching places.
> 
>     4. The tags are not automatically checked inside of the form.

**Comment by Zzz4nder** [comment]
Hey Ashleigh thanks for the review

1. So for the the first point you brought up
yes i merged weird that’s why the its outdated version of the project. I might have to manually copy and paste my files into main and push from there so it doesn't mess anything up

2. I can change the the placeholder element to a value
﻿
﻿3. The dates are renaming the same. I thought that since the drive is being edited the date of the drive should not change. 
﻿I ran into the same issue while editing drives. From my understanding its how the drives are being populated into the table. The table in /userprofile page has a drive # which does not exist in our database (sql). Every time we edit a drive, Ive noticed that the updated row goes to the bottom of the table in Datagrip. Unless we numerically order them in our database, or populate the table by oldest date then The drives will keep moving to the bottom after being updated.
﻿I could fix this issue but It doesn't a fault of my own code. That would be another branch/feature.
﻿
﻿4. Adding a check next to the tags that are already selected would be a a good bit of more work that only adds to the a ease of use. I figured I could add it later since some people were waiting on my to finish the edit drive functionality and it functionally works. In my app.py I did add the tags that were already selected, I just did not checked them on the edit drive page.

**Comment by Zzz4nder** [comment]
Okay I added the values instead of place holders and checked tags that were already selected

**Pull request merged**
