### PR TITLE
User profile - Delete a drive

### PR DESCRIPTION
**Pull request by Matt5008906**
- Added user profile dropdown
- did some functionality for posting that/ waiting on sessions which will make things simpler
- added delete a drive based on username and drive id
- added the query for delete a drive
- Delete a drive should be updated & work when Sean gets through the individual drive functionality

(also some of these changes are spaces/testing etc)

### CODE REVIEW

**Comment by Ashleigh0204** [comment]
drop down looks good to me.  I think we need Sean's stuff first before delete will work.  I currently get an error

**Comment by skiser77** [comment]
Hey I wrote the code for all of the individual drive. If you review it I can merge it with main and then you can implement your delete functionality with the code that I wrote. Then I can do your code review matt.

**Comment by Matt5008906** [comment]
Sounds good ill check after class

**Comment by Matt5008906** [comment]
added delete button after edit comment like etc, should be all good

**Comment by skiser77** [comment]
Looks good to me you can go ahead and merge with main!

**Comment by skiser77** [comment]
make sure to delete your branch after you merge with main we have a lot of branches right now that I think we are forgetting to delete after merging with main.

**Pull request merged**
