### PR TITLE
fixed homepage css and footer

### PR DESCRIPTION
**Pull request by Zzz4nder**
Fixed homepage background looking weird on larger monitors. Made Footer stick to bottom of screen.

Only changed CSS and _layout.html.

### CODE REVIEW

**Comment by SandeepVasireddy** [comment]
The html and css seems good. However when I try and access leaderboard I am getting an error with your database. I'm nor sure if you patched it in another request.

This is the error:

   raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column drive.mileage does not exist
LINE 2:                         ROUND(CAST(SUM(drive.mileage) AS NUM...
                                               ^
HINT:  Perhaps you meant to reference the column "drive.milage".
127.0.0.1 - - [19/Apr/2024 14:47:21] "GET /leaderboard HTTP/1.1" 500 -

**Comment by Zzz4nder** [comment]
Hey Sandeep have you updated your database/queries?
There was a typo for Mileage and someone corrected it to Mileage

I believe thats the issue

**Comment by SandeepVasireddy** [comment]
yes your right let me update my database and run it

**Comment by SandeepVasireddy** [comment]
The footer is too intrusive. It covers up the elements at the bottom of the page even after scrolling all the way down.

**Pull request merged**
